### PR TITLE
Fix the loop...

### PR DESCRIPTION
**Pull request by Sophist-UK**
... so that other plugins work as if this was a blog or archive post. See issue #156.

This commit saves the existing loop, creates a new default loop (using the standard loop structure / calls) and then restores the original loop afterwards. (See [codex example](https://codex.wordpress.org/The_Loop#Multiple_Loops_Example_2).)

### CODE REVIEW

**Comment by picandocodigo** [comment]
@Sophist-UK thank you very much for your great contribution, as always :+1: 

I'm testing this locally and I've found an issue. When using LCP in a post, the "Edit Post" link has the wrong ID. This happens both in the post itself and in the index. It's always the same post id for different instances of the "Edit Post" link, so I'm guessing there's something modifying the general loop?

**Comment by Sophist-UK** [comment]
I won't have time to set up a test site to look at this. Do you have a site I can access? Or an annotate screen shot showing the Edit button(s) and which posts they refer to would be a second best.

Also, off abroad for a week or so, and then will have higher priority stuff, so it may have to wait for me to look at it.

**Comment by picandocodigo** [comment]
Ok don't worry, I'll check it out as soon as I get some time to work on it. Thank you very much for your help!

**Comment by picandocodigo** [comment]
@Sophist-UK this seems to have fixed it: 004c1f8ebc1d072a0506c8c05ba19b0c5764dc4c :smiley:

**Comment by Sophist-UK** [comment]
Thanks.

**Pull request merged**
