### PR TITLE
Dynamic pagination

### LINKED ISSUE #83: Pagination -  reduce amount of pages when there are many pages.
http://wordpress.org/support/topic/pagination-with-lots-of-pages

### PR DESCRIPTION
**Pull request by zymeth25**
Added `pagination_padding` parameter and tests for dynamic pagination.

Fixed indentation in lcp-paginator.php and in the tests.

Fixes #83

### CODE REVIEW

**Comment by zymeth25** [comment]
One thing to note is that the padding will not be customisable in the widget. But I think it's fine.

**Comment by picandocodigo** [comment]
@zymeth25 Hello again! Sorry it took so long, but this is going into the new version of LCP :grimacing:
I couldn't find the documentation though, but I will update the docs with the `pagination_padding` parameter information. Thank you very much!

**Comment by zymeth25** [comment]
Hello @picandocodigo That's great

To access the documentation in my fork of the wiki you have to clone it locally, it you just click the link it won't work (thanks Github 😉 )

**Comment by picandocodigo** [comment]
Sorry @zymeth25 but I couldn't find the branch. I added this to the wiki though:

## Pagination padding

You can customize how many pages to show in the pagination with the `pagination_padding` parameter. When using `[catlist pagination=yes]`, we get a pagination like this:

> **1** 2 3 4 5 6 ... 40 >>

If we go to page 12, we see 5 more pages to each side:

> << 1 ... 7 8 9 10 11 **12** 13 14 15 16 17 ... 40 >>

With `pagination_padding`, we can customize the amount of pages for each side. So `[catlist pagination=yes pagination_padding=2]` will show this:

> << 1 ... 10 11 **12** 13 14 ... 40 >>

If you have any more info or anything you want to add, let me know. Thanks!

**Pull request merged**
