### PR TITLE
Updates docs and bumps version to 0.84

### PR DESCRIPTION
**Pull request by picandocodigo**
Klemens, let me know if I missed something!

### CODE REVIEW

**Review by klemens-st — APPROVED** [review]
Looks good to me! 👍

**Comment by picandocodigo** [comment]
@klemens-st all good to go then, right? Feel free to publish the release that generates the tag, and let's see how it goes :smile:

**Comment by klemens-st** [comment]
It worked 🎆 Say farewell to svh ;)

**Comment by picandocodigo** [comment]
Woooooo!  :partying_face: 
Thank you so much! This is going to make things so much easier from now on :smile: 
```
$ sudo apt-get remove subversion
```

**Comment by klemens-st** [comment]
No problem, I just found that action a couple months ago when thinking 'clearly, there must be a way now to avoid subversion' 😆 

One thing that's left is the `assets` directory i svn. You can create a `.wordpress-org` directory in this repo and the deploy action will sync it with the svn `assets` dir. Just in case you want to keep things in one place.

**Comment by picandocodigo** [comment]
Good shout, I'll definitely do that too so we don't need to ever worry about svn again :laughing:

**Comment by picandocodigo** [comment]
Done!
https://github.com/picandocodigo/List-Category-Posts/commit/c2ae12d4cd6cb8b7334c862e92dea9f3a516809b

**Comment by klemens-st** [comment]
Nice! Feels modern without svn relics :p

**Pull request merged**
