### PR TITLE
Fix no tag issue

### LINKED ISSUE #80: No tags issue
When the post has no tag, or a page is opened (which has no tags by nature), the error message is fixed, but the list is not empty, but full, it seems to take "nothing" for "everything". Maybe a little "if posthavetag" or something could avoid this. I think if there is no match, it needs to be empty.

http://wordpress.org/support/topic/detecting-current-tags?replies=8#post-5214337

### PR DESCRIPTION
**Pull request by zymeth25**
This fixes #80 but not by just addressing the issue. I tried to build on the `lcp_should_return_posts` function idea that I found in `lcp_catlist.php` to introduce a prototype of a framework that deals with similar problems. 

This is not the most elegant solution but I tried to do it with as few changes as possible. Feedback is welcome so I can make it better before merging.

### CODE REVIEW

**Comment by picandocodigo** [comment]
Great! I'm having issues with indentation myself. `php-mode` is a mess in Emacs, but I still struggle to make it consistent. I'll review this as soon as possible. Thank you!

**Comment by zymeth25** [comment]
Amended the commit as per my previous comment

**Comment by picandocodigo** [comment]
Taking a look at this. Can you please explain the change a bit more? I'm just a bit confused. If you set stuff in `$flag`, then you would not return any posts and allow sticky ones, or would that be parametrisable?

**Comment by zymeth25** [comment]
Yes, if there's anything in `$flags` then nothing will be displayed except sticky posts. That's it. It's a starter solution, I think it can later be developed to allow passing parameters to `lcp_should_display_posts` so that there can be more detailed control.

Thinking about it now I think sticky posts should not be displayed when `$flags` are set...

**Comment by zymeth25** [comment]
If you think this approach is good, I could later add a shortcode parameter or a backend option for the user to decide what to do when there's nothing to display.

**Comment by zymeth25** [comment]
Rebased a bit to resolve conflicts with the current version.

**Comment by zymeth25** [comment]
Closing or now, will reopen sometime later after other things are done.

**Comment by picandocodigo** [comment]
Hey @zymeth25, sorry I didn't review this in time. Feel free to reopen whenever you like!

**Pull request closed without merging**
