### PR TITLE
Refactor custom fields

### PR DESCRIPTION
**Pull request by zymeth25**
#261 was closed but the issue is unresolved so I devised this quick fix. Since it was discussed in that thread I will skip the description here.

Instead of using simple parameters like `meta_key` I'm passing `meta_query`, an array of arrays. This allows for all sorts of magic that WP_Meta_Query has.

### CODE REVIEW

**Comment by picandocodigo** [comment]
@zymeth25 thanks for this! I really appreciate all the work you've been doing for the plugin recently!

From what I understand, using meta_query will allow using customfield_name, customfield_value, customfield_display and customfield_orderby, this last one is not working as expected now, right?

Can you add some info about this to the `readme.txt`? I want to merge this in before putting a new version in wordpress.org with all the pagination fixes and stuff. Thanks!

**Comment by zymeth25** [comment]
@picandogodigo Yes, actually `customfield_display` was never an issue, it was a misunderstanding that I explained in #261. The real problem is the use of `customfield_name`, `customfield_value` and ` customfield_orderby` together. But in this PR I'm using sub-meta queries that the `WP_Meta_Query` class allows. In the current version of the plugin there can be only one `meta_key` defined in `$args`, which is a problem because it can be either the value of `customfield_name` or `customfield_orderby`. Not both. With sub-meta queries we can have both.

I can add an info to the readme that it is possible to use those parameters together now.

**Comment by picandocodigo** [comment]
Awesome, thanks! Yes, if you can add a commit with this info in the readme that would be great.

**Comment by zymeth25** [comment]
Done, hope this is understandable.

**Pull request merged**
