### PR TITLE
Update READMEs and bump version

### PR DESCRIPTION
**Pull request by picandocodigo**
@zymeth25 working on the changelog and version bump, did I miss anything? Also crediting you more for the work you've been doing :clap: :clap: 
Thank you!

### CODE REVIEW

**Comment by zymeth25** [comment]
Actually, you can add info about this to the changelog becuase now all template functions follow this rule (previously not all did).

https://github.com/picandocodigo/List-Category-Posts/wiki/HTML-&-CSS-Customization#templates

**Comment by picandocodigo** [comment]
@zymeth25 I added the info on templates. I think we should be ready to release now. I'm still going through my notifications looking at the issues that have been closed :facepalm:

**Comment by zymeth25** [comment]
@picandocodigo Yeah let's release and make sure there are no issues.

**Comment by picandocodigo** [comment]
@zymeth25 It's out! Updated on my production blog and it's looking good (but to be fair, I use only the most basic functionality :laughing: )

**Pull request merged**
