### PR TITLE
link_titles=false creates plain text...

### PR DESCRIPTION
**Pull request by Sophist-UK**
... rather than unlinked formatted text as you might expect.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
Since I was changing this function anyway, I added fixes for #133 and #143

**Comment by picandocodigo** [comment]
Thanks again!!! \o/

**Comment by Sophist-UK** [comment]
Note:If multi-byte string functions are not enabled, then no other workaround is required as php will not handle multi-byte languages at all and the standard ascii functions will be sufficient.

**Comment by Sophist-UK** [comment]
Fixes #150

**Pull request merged**
