### PR TITLE
Fix PHPUnit tests

### PR DESCRIPTION
**Pull request by boonebgorges**
It appears that, a few years ago, some work was done to set up a PHPUnit testing scaffold. It appears that it doesn't work anymore, or perhaps it never fully did. I've reconfigured the PHPUnit setup so that you can simply run `phpunit` inside of the `list-category-posts` directory (assuming you're running inside of a develop.svn.wordpress.org checkout).

Much of the codebase is not easily testable due to the widespread use of private methods/properties and the lack of publicly accessible getters/setters, but maybe we can worry a bit about that after first getting the basic bootstrap working :)

### CODE REVIEW

**Comment by picandocodigo** [comment]
Hi @boonebgorges, thank you so much for this PR!!! :+1: 

@cfoellmann did the work to integrate with PHP Unit through [wp-repository.codex](https://github.com/wp-repository/wp-repository.codex/). Back then everything was integrated with [Travis](https://travis-ci.org/picandocodigo/List-Category-Posts/) for Continuous Integration, but a change in the wp-repository.codex code made the build break and I haven't fixed it since then. It would be great to have that working again.

I'm sincerely an ignorant when it comes to PHP Unit and Plugins testing on WordPress. I only use PHP for WordPress stuff and I haven't bothered to learn about it.

How can I test your work in my local env? It would be awesome to get this merged in, fix the Travis build, and start writing some decent tests. The plugin wasn't really designed, just built and hacked on till we got where we are now, it's quite a mess :poop: but as you say, we can start worrying on fixing that later (and tests can only help :smile:).

**Comment by boonebgorges** [comment]
Happy to help! There is a bug or two I need to fix for a client, but I was nervous to do it without unit tests :)

> How can I test your work in my local env?

There are a couple ways to do it, but I'd recommend the following. 

1. Follow the instructions at https://make.wordpress.org/core/handbook/automated-testing/ to get set up with core unit tests. Once you're able to run them successfully, move on to step 2.
2. Define an environment variable `WP_DEVELOP_DIR` that points to wherever you installed the WP suite in step 1. Eg: `> export WP_DEVELOP_DIR="/home/bgorges/sites/wpdevelop"`
3. `cd` to the `list-category-posts` directory and run `> $phpunit`.

Let me know if you have any problems. Once this is merged, I'll help you get set up with a config for Travis.

**Comment by bibz** [comment]
@boonebgorges I am wondering, why are you referring to the Core automated testing?
Do you mean that the unit tests of this plugin should also include the whole Core testing set?

As [stated](http://wp-cli.org/blog/plugin-unit-tests.html) by the wp-cli team:
> One of the reasons so few people take the time to write unit tests for plugins they author is that it’s a chore to set everything up. Besides installing PHPUnit, you also have to set up the WordPress testing library, as well as the actual plugin tests configuration files.

[Their proposal](https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests) is a one*-liner `wp scaffold list-cateogry-posts`.

\* OK, *some* lines. You still need to install `phpunit` before hand, and then initialize the test suite with the provided script.

**Comment by bibz** [comment]
Still, your tests would be totally awesome ported to the new code-base :innocent:.

**Comment by boonebgorges** [comment]
@bibz I assume you mean in this comment? https://github.com/picandocodigo/List-Category-Posts/pull/153#issuecomment-91389986

I referred to the core tests as a way of showing @picandocodigo how to get PHPUnit set up on his local machine. That is: once your environment is provisioned so that you can run the core tests, it follows that you could run the tests as I laid them out in this PR. I do not mean to suggest that the core tests themselves should be run as part of list-category-posts.

`wp scaffold plugin-tests list-category-posts` is a great way to get set up with plugin tests. The main difference between what you did and what I did is that I didn't require Vagrant.

**Comment by bibz** [comment]
Yes, you assumed right. And that was a good example.

I did not try to run `phpunit` outside of the virtual machine. That was not the goal as there was already a Vagrant configuration set up.
Maybe an hybrid process would be doable? (Both with and without Vagrant, the former to offer uniformity and the later to assure a wider access.)

**Comment by picandocodigo** [comment]
@bibz @boonebgorges thank you both very much for the work you've done. I wish I could at least buy you both a drink in appreciation :P

Should I close this Pull Request? The `get_default_args()` function I'd like to merge into master and any other stuff that can work with the current testing env. Maybe create a new PR or update this one @boonebgorges?

Thanks guys!!!

**Pull request closed without merging**
