### PR TITLE
Add `customfield_date`, `customfield_before`, `customfield_after` attributes.

### PR DESCRIPTION
**Pull request by likemusic**
Add `customfield_date`, `customfield_before`, `customfield_after` attributes to have possibility to filter custom field with datetime type (in my case for custom post type `event`).

### CODE REVIEW

**Comment by zymeth25** [comment]
Hi @likemusic, thanks for sharing your code. I wanted to start testing and reviewing it but after first glance I had one thought I'd like to discuss first.

What you wrote is basically a sorting system, but it's very specialized because it requires  MySQL's `DATETIME` formatted custom fields to be present in posts we want to work with. So this alone wouldn't be very useful to most of our users because you have hardcoded the date handling.

Don't you think it would be better to avoid duplication and expand the meta query without hardcoding anything? What I'm thinking about is this:

* instead of the shortcodes you proposed, add, for instance, `customfield_compare`, `customfield_greaterthan` and `customfield_lessthan`. As you see this is analogous to your shortcodes but not date specific
* add `customfield_compare_type` that would accept all types that the meta query accepts
* Adapt the code you wrote by removing hardcoded date handling and working with the type specified by the user.

What do you think?

**Comment by likemusic** [comment]
@zymeth25 I fully agree with all of the above. The proposed attributes is more logical and convenient both for using and for impementing.

**Comment by zymeth25** [comment]
Nice! That would be a good new feature I think.

**Comment by zymeth25** [comment]
Do you want to implement it?

**Comment by zymeth25** [comment]
@anthonypero have a look at #328. Until it is merged there is unfortunately no other way to filter by custom date field value range.

**Comment by anthonypero** [comment]
I saw it. I was just hoping :) The other solution, with customfield_compare
is more what I'm looking for. That works like WP_Query

**Comment by picandocodigo** [comment]
I'm closing this in favor of #328.

Thank you @likemusic for opening the PR and starting the conversation. The feature will be available in the next release.

**Comment by anthonypero** [comment]
Hi there, this does not seem to have been committed in the .79 release, which was 13 days ago. Is there an update on when this might be available? Thank you!

**Comment by picandocodigo** [comment]
Hi @anthonypero, the time we have to work on the plugin is limited, so we're trying to make releases as often as it's possible, include as many features as we can, but making sure we test them and review the changes.

So while it didn't go into 0.79, it'll probably go into 0.80 which we'll release as soon as possible. You can help out by testing #328 :smile: 
Cheers!

**Comment by anthonypero** [comment]
Sorry if I came across wrong! I was just asking if there was a regular
release schedule. Thank you.

**Pull request closed without merging**
